---
uuid: dc7488de-f075-4611-b2bd-a77fec5772ca
description: 
title: 에러처리
tags: [javascript]
date: 2021-01-29T15:00:00.000Z
---







throw를 통해 에러를 발생시킬 수 있다.

에러는 호출자 방향으로 전파가 된다.

즉 콜스택(실행컨텍스트 스택)의 아랫방향으로 전파가 된다.

throw된 에러를 캐치하지 못한다면 프로그램은 종료된다.

### Error 객체

```jsx
const error = new Error('new Error!');
throw error;
// Error: new Error!
//     at Object.<anonymous> (F:\WorkSpace\WorkSpace_Web\algorith.js\index.js:1:15)
//     at Module._compile (internal/modules/cjs/loader.js:1137:30)
//     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
//     at Module.load (internal/modules/cjs/loader.js:985:32)
//     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
//     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
//     at internal/main/run_main_module.js:17:47
```

**7가지 생성자함수**

아래의 생성자함수로 생성한 객체의 프로토타입은 모두 Error.prototype을 상속받는다.

[Untitled Database](%E1%84%8B%E1%85%A6%E1%84%85%E1%85%A5%E1%84%8E%E1%85%A5%E1%84%85%E1%85%B5%207a17184232954e1f917297475fa296dc/Untitled%20Database%20c3684f48ff37417a82ba6eee78e64f78.csv)
